name: GitHub-Profile-3D-Contribs

on:
  schedule:
    - cron: "0 18 * * *" # Se ejecuta cada d√≠a a las 18:00
  workflow_dispatch: # Permite ejecutarlo manual
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contribs
    permissions:
      contents: write # IMPORTANTE: Permiso para guardar la imagen
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389105/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "generated 3d stats"
          git push
